language: go
go_import_path: blunt.sh/wtfcmd
go: 1.8
install:
  - go get github.com/mattn/go-isatty
  - go get gopkg.in/yaml.v2

branches:
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

sudo: false
os:
  - osx
  - linux

script:
  - cd $GOPATH/src/blunt.sh/wtfcmd
  - go test blunt.sh/wtfcmd/wtf
  - go run assetbuilder/build.go $(pwd)/assets
  - go install blunt.sh/wtfcmd/wtf

before_deploy:
    - "mv $GOPATH/bin/wtf $GOPATH/bin/wtf.$TRAVIS_OS_NAME"

deploy:
  provider: releases
  api_key:
    - secure: "rPr+P0x15Gb9eLMUldLOdiIOU6IpaVpxZ/pulBZKtqBqOsWLYCATTyJxRB2BDuF25Gw+eT+fU41Gx1qflGNEbjYAM8z/Csa9aDYBND0g6mbeh8VQkPwCRZfR4AfoP8410MZT9A+CMZuIJOou2rUsM1PS0k4P56XXYAqgeciaJ/F1VAoVL5Rsq4pGrmtWaDO7CnrXRZdJbOSGQoSJf19me2nyML8h4/AA6BNcvV+I9FgCpfCiPlN2478fvhKnTDHUHOiiiNFUS9q0GAAHRxaD7hWZAt+4cTqJ+WmK5ZfrfIeWj2SQqmMGBCm6cXPR/ZpCuuauNlwbC+zbO3sZzKAnQ1FwPVOP6ipUUTwvrJTSW8RjoeB9unXjEIGJ1c+14UvBPrlNTRvYueGbkUYVgV6tEWsY9BVlhxwRjrXmrF0tm7buwc4j0Y8064hA8VVl+2mfUrYVlMwOJsXg+WnMZXcv7auBMVY6OeIb55vqTrGL6AckFO2tWQyk+a+lYM2pJq1s+BeYpGEGDsmhRQzC6VBxKs99X92qZASFvxecOMyLnX7S6XNIDFZ1NKJHO2ICbxAKgkwHHbkJs513Y4hCaLNHB6NqS40Hnnn6Rs1qu1Z5d7Zy1xOVM4U/jq7G67/47sMNHX+uL45e/rN8LY1POWwVULJ14aoZzZ0TfHujGYZQWwQ="
  file_glob: true
  file: "$GOPATH/bin/wtf.$TRAVIS_OS_NAME"
  skip_cleanup: true
  on:
    tags: true