language: go
go_import_path: blunt.sh/wtfcmd
go: "1.17"

branches:
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

sudo: false
os:
  - linux

script:
  - cd $GOPATH/src/blunt.sh/wtfcmd
  - go run assetbuilder/build.go $(pwd)/assets
  - go test blunt.sh/wtfcmd/wtf
  - env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o $GOPATH/bin/wtf.exe blunt.sh/wtfcmd/wtf
  - env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o $GOPATH/bin/wtf.osx blunt.sh/wtfcmd/wtf
  - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o $GOPATH/bin/wtf.linux blunt.sh/wtfcmd/wtf
  - env GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o $GOPATH/bin/wtf.linux-arm blunt.sh/wtfcmd/wtf

deploy:
  provider: releases
  api_key:
    secure: "T9pu18VJXtHS90Kx2Ef8o9pr7ljV613oS0XheMh3bBc+3wjdJjDPgGSRImvsN/TOB5qYJUIIOYtaEvjrVmGIPx98wQ+NzYeFcVkfZ8QAUxtXRb2DW67K9Kp9BdLjl203RO1ahIM4h+wcDB/8Moi0/ZMWJmef1b8AGS+Wl1GQbkDRmFVWIvg8ExSzqAvgdyZ2ZJfzeG5BpDImk5CSaBzP3NxVVjA+7ZgRNvPzPqlO8L7mmvBhE2b/ZpLLCz6kAU32yPLoi21SodO6U+Kam+3Rb8Kov9dNj0y6yOX6Ul/gp8pCtq/JcK460qs96gsiDSiSQ8n5Ym7S6GCiA0UQEKIhHztU5G9hbDVSmopbWhZZHXb72ftjOv66tv9t7CEEie7DAHo6EhawHtUME4a373SDUoHym1lvwxf0BgQJMsBf9lCYNWTisZCHLHKXJ6HsnRXphlJvAuD22CWqwyjgW710Bi85/d3c6QsgaDE7PoiJ4S+cVI3SOE2AvF4Ah/jIe+3ij1KAqQaS3FjTqFs7oiuYCB1Wy+oQCV0nWfvUhzUjVlMfr1O1YoyCqYb0FE96jvpOmnldX7eacGSHtXrlUGY1J7CXJaEENL9cL0hgRNPmAAaofcKbYADyKLyPr+RLVa3zXwfhtBIYj43cAwjHocNP8fN+1jZrJB0vHwZEFDYoovY="
  file_glob: true
  file: "$GOPATH/bin/wtf.*"
  skip_cleanup: true
  on:
    tags: true