- name: [install, i]
  cmd:
    bash: |
      go run assetbuilder/build.go $(pwd)/assets && \
      go install -ldflags="-s -w" blunt.sh/wtfcmd/wtf
    powershell: |
      go run assetbuilder/build.go assets
      go install -ldflags="-s -w" blunt.sh/wtfcmd/wtf
  desc: Install the command

- name: [build, b]
  cmd:
    bash: |
      go run assetbuilder/build.go $(pwd)/assets && \
      go build -ldflags="-s -w" -o wtf blunt.sh/wtfcmd/wtf
    powershell: |
      go run assetbuilder/build.go assets
      go build -ldflags="-s -w" -o wtf.exe blunt.sh/wtfcmd/wtf
  desc: Build the command

- name: [test, t]
  cmd: go test blunt.sh/wtfcmd/wtf
  desc: Start tests

- name: [format, f]
  cmd:
    bash: gofmt -s -w *.go
    powershell: foreach ($file in get-ChildItem *.go) { gofmt -s -w $file.fullname }
  desc: Format go code