package assets

// Get returns the asset content by name.
// This file is generated by build.php.
func Get(asset string) string {
	switch asset {
	case "autocomplete.ps1":
		return "# Autocomplete function\r\n$completion_CMDNAME = {\r\n\tparam($commandName, $commandAst, $cursorPosition)\r\n\r\n\t# Params for CMDNAME --autocomplete\r\n\t$cmdline = $commandAst.ToString()\r\n\t$words = @()\r\n\tforeach ($word in $commandAst.CommandElements) {\r\n\t\t$words += $word.ToString()\r\n\t}\r\n\r\n\t# Results\r\n\t$output = CMDNAME --autocomplete $cursorPosition \"$cmdline\" $words | Out-String\r\n\t$output = $output -replace \"\\r\"\r\n\t$output = $output -split \"SEPARATOR\"\r\n\tforeach ($word in $output) {\r\n\t\tif ($word -ne '') {\r\n\t\t\tNew-Object System.Management.Automation.CompletionResult $word, $word, 'ParameterValue', $word\r\n\t\t}\r\n\t}\r\n}\r\n\r\n# Register the TabExpension2 function\r\nif (-not $global:options) { $global:options = @{CustomArgumentCompleters = @{};NativeArgumentCompleters = @{}}}\r\n$global:options['NativeArgumentCompleters']['CMDNAME'] = $completion_CMDNAME\r\n$function:tabexpansion2 = $function:tabexpansion2 -replace 'End\\r\\n{','End { if ($null -ne $options) { $options += $global:options} else {$options = $global:options}'"
	case "autocomplete.sh":
		return "# Call our program to autocomplete\n_CMDNAME_completion_loader() {\n\tlocal string=\"$(CMDPATH --autocomplete $COMP_POINT \"$COMP_LINE\" \"${COMP_WORDS[@]}\")\"\n\tlocal index=0\n\tlocal sep=\"SEPARATOR\"\n\t\n\t# Empty\n\tif [ -z \"$string\" ]; then\n\t\tCOMPREPLY=()\n\t\treturn 0\n\tfi\n\t\n\t# Split into COMPREPLY\n\twhile [ \"$string\" != \"${string#*$sep}\" ]; do\n\t\tCOMPREPLY[$index]=\"${string%%$sep*}\"\n\t\tindex=$((index+1))\n\t\tstring=\"${string#*$sep}\"\n\tdone\n\tCOMPREPLY[$index]=\"$string\"\n}\ncomplete -F _CMDNAME_completion_loader -o default CMDNAME"
	}
	return ""
}