package assets

// Get returns the asset content by name.
// This file is generated by build.php.
func Get(asset string) string {
	switch asset {
	case "autocomplete.ps1":
		return "# Should be used with:\n# $ExecutionContext.InvokeCommand.ExpandString(CMDNAME --autocomplete setup)\n\n# Autocomplete function\n$completion_CMDNAME = {\n\tparam($commandName, $commandAst, $cursorPosition)\n\n\t# Params for CMDNAME --autocomplete\n\t$cmdline = $commandAst.ToString()\n\t$words = @()\n\tforeach ($word in $commandAst.CommandElements) {\n\t\t$words += $word.ToString()\n\t}\n\n\t# Results\n\t$output = CMDNAME --autocomplete $cursorPosition \"$cmdline\" $words | Out-String\n\t$output = $output -replace \"\\r\"\n\t$output = $output -split \"SEPARATOR\"\n\tforeach ($word in $output) {\n\t\tif ($word -ne '') {\n\t\t\tNew-Object System.Management.Automation.CompletionResult $word, $word, 'ParameterValue', $word\n\t\t}\n\t}\n}\n\n# Register the TabExpension2 function\nif (-not $global:options) { $global:options = @{CustomArgumentCompleters = @{};NativeArgumentCompleters = @{}}}\n$global:options['NativeArgumentCompleters']['CMDNAME'] = $completion_CMDNAME\n$function:tabexpansion2 = $function:tabexpansion2 -replace 'End\\r\\n{','End { if ($null -ne $options) { $options += $global:options} else {$options = $global:options}'"
	case "autocomplete.sh":
		return "# Should be used with:\n# eval \"$(CMDNAME --autocomplete setup)\"\n\n# Call our program to autocomplete\n_CMDNAME_completion_loader() {\n\tlocal string=\"$(CMDPATH --autocomplete $COMP_POINT \"$COMP_LINE\" \"${COMP_WORDS[@]}\")\"\n\tlocal index=0\n\tlocal sep=\"SEPARATOR\"\n\t\n\t# Empty\n\tif [ -z \"$string\" ]; then\n\t\tCOMPREPLY=()\n\t\treturn 0\n\tfi\n\t\n\t# Split into COMPREPLY\n\twhile [ \"$string\" != \"${string#*$sep}\" ]; do\n\t\tCOMPREPLY[$index]=\"${string%%$sep*}\"\n\t\tindex=$index+1\n\t\tstring=\"${string#*$sep}\"\n\tdone\n\tCOMPREPLY[$index]=\"$string\"\n}\ncomplete -F _CMDNAME_completion_loader -o default CMDNAME"
	}
	return ""
}