name: Go

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Generate assets
      run: go run assetbuilder/build.go $(pwd)/assets
    - name: Test
      run: go test ./wtf
    - name: Build for windows
      run: env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ./bin/wtf.exe ./wtf
    - name: Build for macos
      run: env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ./bin/wtf.osx ./wtf
    - name: Build for linux
      run: env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ./bin/wtf.linux ./wtf
    - name: Build for linux-arm
      run: env GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o ./bin/wtf.linux-arm ./wtf
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./bin/wtf.*